config/routes.rb
Audioserver::Application.routes.draw do
  resources :examiners

  resources :patients do
    resources :audiograms
  end

  post 'direct_create/:hp_id' => 'patients#direct_create'
  get 'patients/by_hp_id/:hp_id' => 'patients#by_hp_id'
  get 'audiograms/index_of_id/:hp_id' => 'patients#by_hp_id'

end

app/models/audiogram.rb
class Audiogram < ActiveRecord::Base
  belongs_to :patient
  belongs_to :examiner
end

app/controllers/audiograms_controller.rb
class AudiogramsController < ApplicationController
  # GET /patients/:patient_id/audiograms          {:action=>"index", :controller=>"audiograms"}
  # GET /patients.xml
  def index
    @patient = Patient.find(params[:patient_id])
    #@audiograms = @patient.audiograms.all
    @audiograms = @patient.audiograms.order('examdate DESC').all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @patients }
    end
  end

  # GET /patients/:patient_id/audiograms/1
  # GET /patients/1.xml
  def show
    @patient = Patient.find(params[:patient_id])
    @audiogram = @patient.audiograms.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @patient }
    end
  end

  # GET /patients/:patient_id/audiograms/1/edit
  def edit
    @patient = Patient.find(params[:patient_id])
    @audiogram = @patient.audiograms.find(params[:id])
  end

  # POST /patients/:patient_id/audiograms
  # POST /patients.xml
  def create
    @patient = Patient.find(params[:patient_id])
    @audiogram = @patient.audiograms.create(params[:audiogram])

    respond_to do |format|
      if @audiogram.save
        format.html { redirect_to(@audiogram, :notice => 'Audiogram was successfully created.') }
        format.xml  { render :xml => @patient, :status => :created, :location => @patient }
      else
        format.html { render :action => "new" } #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! how shall i do
        format.xml  { render :xml => @audiogram.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /patients/:patient_id/audiograms/1
  # PUT /patients/1.xml
  def update
    @patient = Patient.find(params[:patient_id])
    @audiogram = @patient.audiograms.find(params[:id])

    respond_to do |format|
      if @audiogram.update_attributes(params[:audiogram])
        format.html { redirect_to(@audiogram, :notice => 'Audiogram was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" } #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! how...?
        format.xml  { render :xml => @audiogram.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/:patient_id/audiograms/1
  # DELETE /patients/1.xml
  def destroy
    @patient = Patient.find(params[:patient_id])
    @audiogram = @patient.audiograms.find(params[:id])
    @audiogram.destroy

    respond_to do |format|
      format.html { redirect_to(patient_audiograms_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/audiograms_helper.rb
module AudiogramsHelper

  def mean(mode, audiogram)
    case mode
    when "3"
      result_R = (audiogram.ac_rt_500 + audiogram.ac_rt_1k + audiogram.ac_rt_2k)/3.0 rescue "--"
      result_L = (audiogram.ac_lt_500 + audiogram.ac_lt_1k + audiogram.ac_lt_2k)/3.0 rescue "--"
    when "4"
      result_R = (audiogram.ac_rt_500 + 2 * audiogram.ac_rt_1k + audiogram.ac_rt_2k)/4.0 rescue "--"
      result_L = (audiogram.ac_lt_500 + 2 * audiogram.ac_lt_1k + audiogram.ac_lt_2k)/4.0 rescue "--"
    when "4R"
      result_R = (reg(audiogram, "R", "500") + 2 * reg(audiogram, "R", "1k") + reg(audiogram, "R", "2k"))/4.0 rescue "--"
      result_L = (reg(audiogram, "L", "500") + 2 * reg(audiogram, "L", "1k") + reg(audiogram, "L", "2k"))/4.0 rescue "--"      
    when "6"
      result_R = (audiogram.ac_rt_500 + 2 * audiogram.ac_rt_1k + 2 * audiogram.ac_rt_2k + audiogram.ac_rt_4k)/6.0 rescue "--"
      result_L = (audiogram.ac_lt_500 + 2 * audiogram.ac_lt_1k + 2 * audiogram.ac_lt_2k + audiogram.ac_lt_4k)/6.0 rescue "--"
    end
    result_R = round1(result_R) if result_R.class == Float
    result_L = round1(result_L) if result_L.class == Float
    return {:R => result_R, :L => result_L}
  end

  def reg_id(id)
    r_id = "0" * (10-id.length) + id
    return "#{r_id[0..2]}-#{r_id[3..6]}-#{r_id[7..8]}-#{"%c" % r_id[9]}"
  end

  private
  def reg(audiogram, side, freq)
    case side
    when "R"
      case freq
      when "500"
        (audiogram.ac_rt_500 > 100.0 or audiogram.ac_rt_500_scaleout)?105.0:audiogram.ac_rt_500 rescue nil
      when "1k"
        (audiogram.ac_rt_1k > 100.0 or audiogram.ac_rt_1k_scaleout)?105.0:audiogram.ac_rt_1k rescue nil
      when "2k"
        (audiogram.ac_rt_2k > 100.0 or audiogram.ac_rt_2k_scaleout)?105.0:audiogram.ac_rt_2k rescue nil
      end
    when "L"
      case freq
      when "500"
        (audiogram.ac_lt_500 > 100.0 or audiogram.ac_lt_500_scaleout)?105.0:audiogram.ac_lt_500 rescue nil
      when "1k"
        (audiogram.ac_lt_1k > 100.0 or audiogram.ac_lt_1k_scaleout)?105.0:audiogram.ac_lt_1k rescue nil
      when "2k"
        (audiogram.ac_lt_2k > 100.0 or audiogram.ac_lt_2k_scaleout)?105.0:audiogram.ac_lt_2k rescue nil
      end
    end
  end

  def round1(r)  # 小数点1位で四捨五入
    rr = r * 10.0
    rr = rr.round
    return (rr / 10.0)
  end

end

app/views/audiograms/index.html.erb
<h1>聴力検査結果一覧 (ID: <%= reg_id(@patient.hp_id) %>)</h1>

<table>
  <tr class="colored">
    <th></th>
    <th>検査日 Examdate</th>
    <!-- th>Image location</th -->
    <th>検査図 Thumbnail</th>
    <th>4分法平均 mean4</th>
    <th>コメント Comment</th>
    <th></th>
    <!-- th>Manual input</th -->
  </tr>

<%# form_tag :action => 'select' do %>

<% @audiograms.each do |audiogram| %>
  <tr class="<%= cycle("", "colored") %>">
    <!-- cycle は周期的に繰り返す文字列を出力する -->
    <td><%#= check_box_tag "selected[]", audiogram.id %><br><a href="#search">▼</a></td>
    <td><%#=h audiogram.examdate.strftime("%Y/%m/%d") %><br><%# =h audiogram.examdate.strftime("%X/%a") %> <%=h audiogram.examdate.strftime("%Y/%m/%d") %><br><%=h audiogram.examdate.strftime("%X") %></td>
    <!-- td><%#=h audiogram.image_location %></td -->
    <td><%= link_to(image_tag(audiogram.image_location.sub("graphs", "thumbnails")),\
      :action => "show", :id => audiogram.id )%></td>
    <td>R: <%=h mean("4R", audiogram)[:R] %><br>L: <%=h mean("4R", audiogram)[:L] %></td>
      <!-- helper method is put at app/helpers/audiograms_helper.rb -->
    <td><%=h audiogram.comment %></td>
    <!-- td><%#=h audiogram.manual_input %></td -->
    <td><%= link_to 'Show', :action => "show", :id => audiogram.id %><br>
        <% if audiogram.manual_input %><%= link_to 'Edit', edit_patient_audiogram_path(audiogram) %>
        <% else %><%= "cannot edit" %><% end %><br>
        <%= link_to 'Destroy', [audiogram.patient, audiogram], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<a name="search"></a>
<%#= submit_tag 'select 2 audiograms' %>
<%# end %>

<br />
<!-- hr -->

<%#= link_to "New audiogram for ID:#{reg_id(@patient.hp_id)}", :action => "new_for_id", \
      :id => @selected_id %>

<%# form_tag :action => 'search' do %>
  <%#= text_field "condition", "key" %>
  <%#= submit_tag 'Search' %>
<%# end %>

app/views/audiograms/show.html.erb
<p id="notice"><%= notice %></p>

<h1>ID: <%=h reg_id(@patient.hp_id) %>
<%= link_to '[結果一覧へ]', patient_audiograms_path(@patient) %> </h1>
検査日: <%=h @audiogram.examdate %> / 修正日: <%=h @audiogram.updated_at %>

<table>
<tr><td colspan="9"><%= image_tag(@audiogram.image_location) %></td>
    <td rowspan="1">
      <table>
      <tr><th colspan="2">平均値 mean</th></tr>
      <tr><th colspan="2">3分法</th></tr>
      <tr><th>Rt:</th><td><%=h mean("3", @audiogram)[:R] %></td></tr>
      <tr><th>Lt:</th><td><%=h mean("3", @audiogram)[:L] %></td></tr>
      <tr><th colspan="2"></th></tr>
      <% mean4 = mean("4", @audiogram) %>
      <% mean4R = mean("4R", @audiogram) %>
      <% mean4_match = (mean4 == mean4R) %>
      <tr><th colspan="2">4分法<%=h "<br>(cut offなし)" if not mean4_match %></th></tr>
      <tr><th>Rt:</th><td><%=h mean4[:R] %>
                          <%=h "(#{mean4R[:R]})" if not mean4_match %>)</td></tr>
      <tr><th>Lt:</th><td><%=h mean4[:L] %>
                          <%=h "(#{mean4R[:L]})" if not mean4_match %>)</td></tr>
      <tr><th colspan="2"></th></tr>
      <tr><th colspan ="2">6分法</th></tr>
      <tr><th>Rt:</th><td><%=h mean("6", @audiogram)[:R] %></td></tr>
      <tr><th>Lt:</th><td><%=h mean("6", @audiogram)[:L] %></td></tr>
      </table>
    </td></tr>
<tr><td>
      <tr><th colspan="9">マスキング条件</th> <th>検査コメント</th></tr>
      <tr> <th>mode</th> <th>side</th> <th>125Hz</th> <th>250Hz</th> <th>500Hz</th> 
                            <th>1kHz</th> <th>2kHz</th> <th>4kHz</th> <th>8kHz</th>
           <td rowspan="5"><%=h @audiogram.comment %></td></tr>
      <tr><td>Air</td> <td>Rt</td>
          <td><%=h @audiogram.mask_ac_rt_125.round %></td>
          <td><%=h @audiogram.mask_ac_rt_250.round %></td>
          <td><%=h @audiogram.mask_ac_rt_500.round %></td>
          <td><%=h @audiogram.mask_ac_rt_1k.round %></td>
          <td><%=h @audiogram.mask_ac_rt_2k.round %></td>
          <td><%=h @audiogram.mask_ac_rt_4k.round %></td>
          <td><%=h @audiogram.mask_ac_rt_8k.round %></td></tr>
      <tr><td></td> <td>Lt</td>
          <td><%=h @audiogram.mask_ac_lt_125.round %></td>
          <td><%=h @audiogram.mask_ac_lt_250.round %></td>
          <td><%=h @audiogram.mask_ac_lt_500.round %></td>
          <td><%=h @audiogram.mask_ac_lt_1k.round %></td>
          <td><%=h @audiogram.mask_ac_lt_2k.round %></td>
          <td><%=h @audiogram.mask_ac_lt_4k.round %></td>
          <td><%=h @audiogram.mask_ac_lt_8k.round %></td></tr>
      <tr><td>Bone</td> <td>Rt</td>
       `   <td></td>
           <td><%=h @audiogram.mask_bc_rt_250.round %></td>
           <td><%=h @audiogram.mask_bc_rt_500.round %></td>
           <td><%=h @audiogram.mask_bc_rt_1k.round %></td>
           <td><%=h @audiogram.mask_bc_rt_2k.round %></td>
           <td><%=h @audiogram.mask_bc_rt_4k.round %></td>
           <td><%=h @audiogram.mask_bc_rt_8k.round %></td></tr>
      <tr><td></td> <td>Lt</td>
           <td></td>
           <td><%=h @audiogram.mask_bc_lt_250.round %></td>
           <td><%=h @audiogram.mask_bc_lt_500.round %></td>
           <td><%=h @audiogram.mask_bc_lt_1k.round %></td>
           <td><%=h @audiogram.mask_bc_lt_2k.round %></td>
           <td><%=h @audiogram.mask_bc_lt_4k.round %></td>
           <td><%=h @audiogram.mask_bc_lt_8k.round %></td></tr>
    </td>
</table>

<p>
<form name="Form1" style="margin:1ex">
    <input type="button" name="PrintButton" value="印刷" onclick="printout()"/>　
</form>
<%= link_to '検査一覧へ to Index', patient_audiograms_path(@patient) %> <br>