config/routes.rb
Audioserver::Application.routes.draw do
  resources :examiners

  resources :patients do
    resources :audiograms
  end

  post 'direct_create/:hp_id' => 'patients#direct_create'
  get 'patients/by_hp_id/:hp_id' => 'patients#by_hp_id'
  get 'audiograms/index_of_id/:hp_id' => 'patients#by_hp_id'

end

app/models/examiner.rb
class Examiner < ActiveRecord::Base
  has_many :audiograms
  has_many :patients, :through => :audiograms
end

app/controllers/examiners_controller.rb
class ExaminersController < ApplicationController
  # GET /examiners
  # GET /examiners.xml
  def index
    @examiners = Examiner.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @examiners }
    end
  end

  # GET /examiners/1
  # GET /examiners/1.xml
  def show
    @examiner = Examiner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @examiner }
    end
  end

  # GET /examiners/new
  # GET /examiners/new.xml
  def new
    @examiner = Examiner.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @examiner }
    end
  end

  # GET /examiners/1/edit
  def edit
    @examiner = Examiner.find(params[:id])
  end

  # POST /examiners
  # POST /examiners.xml
  def create
    @examiner = Examiner.new(params[:examiner])

    respond_to do |format|
      if @examiner.save
        format.html { redirect_to(@examiner, :notice => 'Examiner was successfully created.') }
        format.xml  { render :xml => @examiner, :status => :created, :location => @examiner }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @examiner.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /examiners/1
  # PUT /examiners/1.xml
  def update
    @examiner = Examiner.find(params[:id])

    respond_to do |format|
      if @examiner.update_attributes(params[:examiner])
        format.html { redirect_to(@examiner, :notice => 'Examiner was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @examiner.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /examiners/1
  # DELETE /examiners/1.xml
  def destroy
    @examiner = Examiner.find(params[:id])
    @examiner.destroy

    respond_to do |format|
      format.html { redirect_to(examiners_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/examiners_helper.rb
module ExaminersHelper
end

app/views/examiners/_form.html.erb
<%= form_for(@examiner) do |f| %>
  <% if @examiner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@examiner.errors.count, "error") %> prohibited this examiner from being saved:</h2>

      <ul>
      <% @examiner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :worker_id %><br />
    <%= f.text_field :worker_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/examiners/edit.html.erb
<h1>Editing examiner</h1>

<%= render 'form' %>

<%= link_to 'Show', @examiner %> |
<%= link_to 'Back', examiners_path %>

app/views/examiners/index.html.erb
<h1>Listing examiners</h1>

<table>
  <tr>
    <th>Worker</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @examiners.each do |examiner| %>
  <tr>
    <td><%= examiner.worker_id %></td>
    <td><%= link_to 'Show', examiner %></td>
    <td><%= link_to 'Edit', edit_examiner_path(examiner) %></td>
    <td><%= link_to 'Destroy', examiner, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Examiner', new_examiner_path %>

app/views/examiners/new.html.erb
<h1>New examiner</h1>

<%= render 'form' %>

<%= link_to 'Back', examiners_path %>

app/views/examiners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Worker:</b>
  <%= @examiner.worker_id %>
</p>


<%= link_to 'Edit', edit_examiner_path(@examiner) %> |
<%= link_to 'Back', examiners_path %>